export const APPOINTMENT_DETAIL_COPY = {
  breadcrumbRoot: "Citas",
  patient: "Paciente",
  employee: "Profesional",
  treatments: "Tratamientos",
  notes: "Notas",
  appointmentDetails: "Detalles de la cita",
  noNotes: "Sin notas.",
  noTreatments: "Sin tratamientos.",
  noPhone: "Sin teléfono",
  back: "Volver",
  edit: "Editar cita",
  notFound: "No se encontró la cita.",
  loadError: "No se pudo cargar la cita.",
  statusError: "No se pudo actualizar el estado de la cita.",
  statusSuccess: "Estado de la cita actualizado.",
  date: "Fecha",
  time: "Hora",
  status: "Estado",
  created: "Creada",
  reminder: "Recordatorio WhatsApp",
  reminderScheduled: "Pendiente de envío automático",
  reminderSent: "Enviado correctamente",
  noReminder: "Sin recordatorio",
  reminderSendManual: "Enviar ahora",
  reminderSending: "Enviando...",
  reminderManualSuccess: "Recordatorio enviado por WhatsApp.",
  reminderManualError: "No se pudo enviar el recordatorio.",
  reminderSkipped: {
    clinica_no_elegible:
      "Los recordatorios están desactivados o falta el número de envío en Ajustes.",
    clinica_sin_numero: "Falta el número de envío de WhatsApp en Ajustes.",
    paciente_sin_telefono: "Este paciente no tiene teléfono.",
    sin_citas_en_ventana: "La cita ya no admite recordatorio.",
    error_consulta_citas: "No se pudo leer la cita.",
    desconocido: "No se envió el recordatorio.",
  },
  totalDuration: "Duración total",
  total: "Total",
  materials: "Materiales",
  materialsDefault: "Según tratamiento",
  materialsOverride: "Personalizados para esta cita",
  materialsConsumed: "Materiales consumidos",
  noMaterials: "Sin materiales asignados.",
  editMaterials: "Personalizar materiales",
  materialsDialogTitle: "Materiales de la cita",
  materialsDialogDescription:
    "Define los materiales que se consumirán al completar esta cita. Si no añades ninguno, se usarán los del tratamiento.",
  materialsSave: "Guardar",
  materialsSaving: "Guardando…",
  materialsCancel: "Cancelar",
  materialsSuccess: "Materiales actualizados.",
  materialsError: "No se pudieron guardar los materiales.",
  materialsLoadError: "No se pudieron cargar los materiales.",
  resetToDefault: "Usar materiales del tratamiento",
  markCompleted: "Marcar como completada",
  confirm: "Confirmar cita",
  cancel: "Cancelar cita",
  confirmCancelTitle: "Cancelar cita",
  confirmCancelDescription:
    "La cita quedará marcada como cancelada. Esta acción no se puede deshacer.",
  confirmCancel: "Confirmar cancelación",
  cancelPending: "Cancelando…",
  cancelDialogCancel: "Volver",
  delete: "Eliminar cita",
  deleteTitle: "Eliminar cita",
  deleteDescription:
    "¿Está seguro de eliminar esta cita? Esta acción no se puede deshacer.",
  deleteRestoreStock: "Reponer los materiales descontados del stock",
  deleteConfirm: "Eliminar definitivamente",
  deletePending: "Eliminando…",
  deleteSuccess: "Cita eliminada correctamente.",
  deleteError: "No se pudo eliminar la cita.",
  moreActions: "Más acciones",
  menuSections: {
    appointment: "Cita",
    status: "Estado",
    danger: "Peligro",
  },
} as const;
