export const APPOINTMENT_DETAIL_COPY = {
  patient: "Paciente",
  employee: "Profesional",
  treatments: "Tratamientos",
  notes: "Notas",
  appointmentDetails: "Detalles de la cita",
  noNotes: "Sin notas.",
  noTreatments: "Sin tratamientos.",
  noPhone: "Sin teléfono",
  back: "Volver",
  edit: "Editar cita",
  notFound: "No se encontró la cita.",
  loadError: "No se pudo cargar la cita.",
  statusError: "No se pudo actualizar el estado de la cita.",
  statusSuccess: "Estado de la cita actualizado.",
  date: "Fecha",
  time: "Hora",
  status: "Estado",
  created: "Creada",
  reminder: "Recordatorio",
  reminderScheduled: "24 h antes",
  reminderSent: "Enviado",
  noReminder: "Sin recordatorio",
  totalDuration: "Duración total",
  total: "Total",
  materials: "Materiales",
  materialsDefault: "Según tratamiento",
  materialsOverride: "Personalizados para esta cita",
  materialsConsumed: "Materiales consumidos",
  noMaterials: "Sin materiales asignados.",
  editMaterials: "Personalizar materiales",
  materialsDialogTitle: "Materiales de la cita",
  materialsDialogDescription:
    "Define los materiales que se consumirán al completar esta cita. Si no añades ninguno, se usarán los del tratamiento.",
  materialsSave: "Guardar",
  materialsSaving: "Guardando…",
  materialsCancel: "Cancelar",
  materialsSuccess: "Materiales actualizados.",
  materialsError: "No se pudieron guardar los materiales.",
  materialsLoadError: "No se pudieron cargar los materiales.",
  resetToDefault: "Usar materiales del tratamiento",
  markCompleted: "Marcar como completada",
  cancel: "Cancelar cita",
  confirmCancelTitle: "Cancelar cita",
  confirmCancelDescription:
    "La cita quedará marcada como cancelada. Esta acción no se puede deshacer.",
  confirmCancel: "Confirmar cancelación",
  cancelPending: "Cancelando…",
  cancelDialogCancel: "Volver",
  moreActions: "Más acciones",
} as const;
