export const PATIENT_GALLERY_COPY = {
  title: "Galería",
  photosCount: (count: number) => `${count} fotos`,
  actions: {
    upload: "Subir fotos",
    beforeAfter: "Crear antes y después",
    more: "Más acciones",
    export: "Exportar galería",
    cancelSelection: "Cancelar selección",
    compare: "Comparar seleccionadas",
  },
  filters: {
    all: "Todas",
    allCategories: "Todas las categorías",
    allPhases: "Todas las fases",
    search: "Buscar fotos...",
    searchClear: "Limpiar búsqueda",
    category: "Categoría",
    sort: "Orden",
    sortRecent: "Más recientes",
    sortOldest: "Más antiguas",
  },
  phases: {
    antes: "Antes",
    durante: "Durante",
    despues: "Después",
  },
  thumbActions: {
    view: "Ver foto",
    delete: "Eliminar",
    select: "Seleccionar",
  },
  empty: "No hay fotos que coincidan con los filtros seleccionados.",
  emptyGallery: "Este paciente aún no tiene fotos en la galería.",
  loadMore: "Cargar más",
  errors: {
    load: "No se pudieron cargar las fotos del paciente.",
  },
  selection: {
    title: "Selecciona dos fotos",
    hint: (count: number) => `${count}/2 fotos seleccionadas`,
  },
  uploader: {
    title: "Subir foto",
    description: "Añade una imagen a la galería del paciente.",
    dropzone: "Arrastra una imagen aquí o selecciónala",
    dropzoneActive: "Suelta la imagen para subirla",
    chooseFile: "Seleccionar archivo",
    previewAlt: "Vista previa de la imagen",
    fields: {
      category: "Categoría",
      phase: "Fase",
      treatment: "Tratamiento",
      capturedAt: "Fecha de captura",
      notes: "Notas",
    },
    phasePlaceholder: "Sin fase",
    treatmentPlaceholder: "Sin tratamiento",
    submit: "Subir foto",
    pending: "Subiendo...",
    success: "Foto subida correctamente",
    error: "No se pudo subir la foto",
    validation: {
      fileRequired: "Selecciona una imagen para continuar.",
      clinicRequired: "No hay una clínica activa.",
    },
    progress: (value: number) => `Subiendo... ${value}%`,
  },
  viewer: {
    previous: "Foto anterior",
    next: "Foto siguiente",
    close: "Cerrar visor",
    delete: "Eliminar foto",
    metadata: {
      capturedAt: "Fecha",
      category: "Categoría",
      phase: "Fase",
      notes: "Notas",
    },
    emptyMetadata: "—",
  },
  beforeAfter: {
    title: "Comparativa antes y después",
    before: "Antes",
    after: "Después",
    close: "Cerrar comparativa",
    swap: "Intercambiar lados",
    orientationLabel: "Orientación de la comparativa",
    orientationHorizontal: "Comparación horizontal",
    orientationVertical: "Comparación vertical",
    sliderLabel: "Comparar imágenes",
  },
  delete: {
    title: "Eliminar foto",
    description:
      "Esta acción eliminará la foto de la galería y del almacenamiento.",
    confirm: "Eliminar",
    cancel: "Cancelar",
    pending: "Eliminando...",
    success: "Foto eliminada",
    error: "No se pudo eliminar la foto",
  },
} as const;
