export const PATIENT_GALLERY_COPY = {
  title: "Galería",
  photosCount: (count: number) => `${count} imágenes`,
  actions: {
    upload: "Subir imágenes",
    beforeAfter: "Crear antes y después",
    more: "Más acciones",
    export: "Exportar galería",
    cancelSelection: "Cancelar selección",
    compare: "Comparar seleccionadas",
  },
  filters: {
    all: "Todas",
    allPhases: "Todas las fases",
    search: "Buscar imágenes...",
    searchClear: "Limpiar búsqueda",
    phase: "Fase",
    sort: "Orden",
    sortRecent: "Más recientes",
    sortOldest: "Más antiguas",
  },
  filterLabels: {
    search: "Buscar imagen",
    phase: "Fase",
    sort: "Orden",
  },
  density: {
    label: "Densidad de la galería",
    compact: "Compacta",
    comfortable: "Media",
    large: "Grande",
  },
  phases: {
    antes: "Antes",
    durante: "Durante",
    despues: "Después",
  },
  thumbActions: {
    view: "Ver imagen",
    delete: "Eliminar",
    select: "Seleccionar",
  },
  empty: "No hay imágenes que coincidan con los filtros seleccionados.",
  emptyGallery: "Este paciente aún no tiene imágenes en la galería.",
  loadMore: "Cargar más",
  errors: {
    load: "No se pudieron cargar las imágenes del paciente.",
  },
  selection: {
    title: "Selecciona dos imágenes",
    hint: (count: number) => `${count}/2 imágenes seleccionadas`,
  },
  uploader: {
    title: "Subir imágenes",
    description: "Añade imágenes a la galería del paciente.",
    dropzone: "Arrastra imágenes aquí o selecciónalas",
    dropzoneActive: "Suelta las imágenes para subirlas",
    chooseFile: "Seleccionar archivos",
    addMore: "Añadir más",
    previewAlt: "Vista previa de la imagen",
    fields: {
      phase: "Fase",
      treatment: "Tratamiento",
      capturedAt: "Fecha de la imagen",
      notes: "Notas",
    },
    phasePlaceholder: "Sin fase",
    treatmentPlaceholder: "Sin tratamiento",
    submit: "Subir imágenes",
    pending: "Subiendo...",
    success: (count: number) =>
      `${count} imagen${count === 1 ? "" : "es"} subida${count === 1 ? "" : "s"} correctamente`,
    error: "No se pudieron subir las imágenes",
    validation: {
      fileRequired: "Selecciona al menos una imagen para continuar.",
      clinicRequired: "No hay una clínica activa.",
      formInvalid: "Revisa los campos marcados antes de continuar.",
    },
    progress: (current: number, total: number) =>
      `Subiendo imagen ${current} de ${total}...`,
  },
  viewer: {
    previous: "Imagen anterior",
    next: "Imagen siguiente",
    close: "Cerrar visor",
    delete: "Eliminar imagen",
    metadata: {
      capturedAt: "Fecha de la imagen",
      phase: "Fase",
      notes: "Notas",
    },
    emptyMetadata: "—",
  },
  beforeAfter: {
    title: "Comparativa antes y después",
    before: "Antes",
    after: "Después",
    close: "Cerrar comparativa",
    swap: "Intercambiar lados",
    orientationLabel: "Orientación de la comparativa",
    orientationHorizontal: "Comparación horizontal",
    orientationVertical: "Comparación vertical",
    sliderLabel: "Comparar imágenes",
  },
  delete: {
    title: "Eliminar imagen",
    description:
      "Esta acción eliminará la imagen de la galería y del almacenamiento.",
    confirm: "Eliminar",
    cancel: "Cancelar",
    pending: "Eliminando...",
    success: "Imagen eliminada",
    error: "No se pudo eliminar la imagen",
  },
} as const;
